global:
    scrape_interval: 15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: tunnel-server
      static_configs:
        - targets:
            - 127.0.0.1:8001
      metrics_path: /metrics
      scrape_interval: 5s
      scrape_timeout: 5s
    - job_name: tunnel-client-pop
      static_configs:
        - targets:
            - '[::1]:15323'
            - 185.209.178.197:15323
            - 35.77.76.220:15323
            - 67.213.115.179:15323
      metrics_path: /metrics
      scrape_interval: 5s
      scrape_timeout: 5s
